/**
 * @note Unrolling vs LOOP on 8086/8088 - measured trade-offs.
 *
 * LOOP has a fixed per-iteration cost regardless of what it guards
 * (17 cycles taken, 5 not taken - Intel's published 8086 timings).
 * Unrolling removes that cost entirely, at the price of code size.
 * How good a trade that is depends entirely on how large the fixed
 * LOOP overhead is RELATIVE to the body it's wrapping - the same
 * technique pays off very differently depending on iteration count
 * and body weight, as the two cases below show:
 *
 * 6-bit shift rescale (fxp_mul / fxp_div, double-precision shift
 * emulating SHRD/SHLD, 6 iterations of a 2-instruction body):
 *
 *   |            | Looped | Unrolled |
 *   |------------|--------|----------|
 *   | Cycles     |    118 |       24 |
 *   | Bytes      |      9 |       24 |
 *
 *   ~5x faster for 15 extra bytes (~6.3 cycles saved per extra byte).
 *   LOOP alone cost almost as much as the entire unrolled body.
 *
 * 16-bit sqrt extraction (fxp_sqrt, digit-by-digit method, 16
 * iterations of a ~10-instruction body):
 *
 *   |            | Looped | Unrolled |
 *   |------------|--------|----------|
 *   | Cycles     |   ~836 |     ~576 |
 *   | Bytes      |    ~22 |     ~240 |
 *
 *   ~31% faster for ~218 extra bytes (~1.2 cycles saved per extra
 *   byte) - a markedly worse trade than the shift case above.
 */
#include "fxp_operators.h"
#include "fxp_types.h"
#include "fxp_limits.h"

fxp16_t fxp_mul(fxp16_t lhs, fxp16_t rhs) {
    __asm {
        .8086
        mov     bx, dx
        imul    bx                      ; DX:AX = lhs * rhs
        cmp     dx, 31                  ; will the hi word overflow 10.6?
        jg      INF                     ; yes clamp
        cmp     dx, -32                 ; will the hi word undeflow 10.6?
        jl      NINF                    ; yes clamp

        sar     dx, 1                   ; emulating SHRD (80386) on 8086/8088
        rcr     ax, 1                   ; unrolled CX 6 LOOP double-precision shift right
        sar     dx, 1                   ; uses 24 instead of 118 cycles
        rcr     ax, 1                   ; shift right DX:AX as 32 bits
        sar     dx, 1
        rcr     ax, 1
        sar     dx, 1
        rcr     ax, 1
        sar     dx, 1
        rcr     ax, 1
        sar     dx, 1
        rcr     ax, 1

        jmp     END
INF:    mov     ax, FXP_MAX             ; clamp result to 10.6 +infinity (+511.984)
        jmp     END
NINF:   mov     ax, FXP_MIN             ; clamp result to 10.6 - infinity(-512.000)

END:

    }
}

/**
* @note  INT 0 is generated by IDIV or DIV when the result won't fit into the destination, or the divisor is 0.
* The 8088, 8086, V20, and V30 push the CS:IP of the instruction *FOLLOWING* the DIV
* or IDIV instruction that generated the division-by-zero error condition.
* Thus, execution will continue.
* The 80286 and 80386, however, push the CS:IP of the *SAME* DIV or IDIV instruction and get
* stuck in an infinite loop!
* However, DOS sidesteps the issue with its INT 0 handler that results in an uncontrolled program termination.
* No cleanup, no save, user is dumped straight back to the DOS prompt.
*/
fxp16_t fxp_div(fxp16_t lhs, fxp16_t rhs) {
    __asm {
		.8086
		mov		bx, dx
		cwd		                        ; DX:AX = sign-extend AX

		mov		cx, FXP_FRACTIONAL_BITS
_SHLD:	sal		ax, 1			        ; shift left DX:AX as 32 bits
		rcl		dx, 1				    ; ...
		loop	_SHLD					; emulate the SHLD (80386) instruction

		idiv	bx						; 80286 and 80386 divide 0 or quotient too large fit destination -> inf loop!
	}
}

/**
 * computes the fixed point remainder of dividing x by y
 */
fxp16_t fxp_mod(fxp16_t x, fxp16_t y) {
    __asm {
        .8086
        mov bx, dx
        cwd                             ; sign-extend x into dx:ax
        idiv    bx                      ; dx = remainder (returned), ax = quotient (discarded)
        mov     ax, dx                  ; move remainder into ax return
    }
}

/**
 * Computes y = sqrt(x) via widen-then-integer-sqrt: the raw value is shifted left by FXP_FRACTIONAL_BITS before extraction,
 * which yields a result already correctly scaled to 10:6 - not merely close, but the exact floor of the true value at this
 * format's own resolution (verified exhaustively against a double-precision oracle across every representable non-negative input)
 * @see test_fxp_sqrt.c
 *
 * The extraction itself is a division-free, shift-and-subtract binary digit-by-digit method:
 * one result bit is produced per iteration (16 iterations total, matching fxp16_t's own bit width exactly),
 * using only shifts, compares, and subtracts - no IDIV anywhere near it, deliberately, given the trouble already had getting fxp_div
 * safe across 8086 through 80286+.
 *
 * @note Origins. The specific software formulation traces to Martin Guy's "Square Root by Abacus Algorithm" (UKC,
 * June 1985), itself adapted from a method for computing square roots by hand on a Chinese abacus, described in a book by C.C. Woo
 * (following Kwa Tak Ming's 1922 original): "The Fundamental Operations in Bead Arithmetic". A physical copy survives in the
 * SOAS University of London library, of all the unlikely places for an 8086 fixed-point game library's ancestry to end up!
 *
 * Negative input has no real result. Rather than return a silent  placeholder (0, or some other value that looks superficially valid
 * and quietly propagates), this is treated as a genuine caller bug: a deliberate INT 0 is raised, invoking DOSFXP's own panic handler
 * (see dosfxp_int0_handler) and terminating the program with a clear message rather than continuing on bad data.
 */
fxp16_t fxp_sqrt(fxp16_t x) {
    __asm {
        .8086
        or      ax, ax                  ; test sign of x
        jns     SQRT                    ; non-negative -> continue normally
        int     0                       ; negative -> deliberate panic (see fxp_sqrt's header comment)

SQRT:   xor     dx, dx                  ; zero-extend x into dx:ax (x is >=0, confirmed above)

        shl     ax, 1                   ; widen: build W = x_raw << FXP_FRACTIONAL_BITS (6)
        rcl     dx, 1                   ; unrolled - same small-shift trade already proven
        shl     ax, 1                   ; worthwhile for fxp_mul/fxp_div's 6-bit rescales
        rcl     dx, 1
        shl     ax, 1
        rcl     dx, 1
        shl     ax, 1
        rcl     dx, 1
        shl     ax, 1
        rcl     dx, 1
        shl     ax, 1
        rcl     dx, 1                   ; dx:ax = W, ready for extraction

        xor     bx, bx                  ; rem = 0
        xor     si, si                  ; root = 0

        shl     ax, 1                   ; feed 2 bits of W into rem, one bit at a time
        rcl     dx, 1                   ; (no single instruction does this on 8086 -
        rcl     bx, 1                   ; each carry-chain step moves exactly one bit)
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1                   ; root <<= 1 (make room for this iteration's guess bit)
        mov     di, si                  ; di = candidate, built from the shifted root
        shl     di, 1
        or      di, 1                   ; candidate = (root<<1)|1
        cmp     bx, di                  ; can we afford to subtract this candidate?
        jb      SKIP1                   ; no - leave this root bit as 0
        sub     bx, di                  ; yes - rem -= candidate
        or      si, 1                   ; and set this iteration's root bit to 1

SKIP1:  shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP2
        sub     bx, di
        or      si, 1

SKIP2:  shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP3
        sub     bx, di
        or      si, 1

SKIP3:  shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP4
        sub     bx, di
        or      si, 1

SKIP4:  shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP5
        sub     bx, di
        or      si, 1

SKIP5:  shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP6
        sub     bx, di
        or      si, 1

SKIP6:  shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP7
        sub     bx, di
        or      si, 1

SKIP7:  shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP8
        sub     bx, di
        or      si, 1

SKIP8:  shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP9
        sub     bx, di
        or      si, 1

SKIP9:  shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP10
        sub     bx, di
        or      si, 1

SKIP10: shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP11
        sub     bx, di
        or      si, 1

SKIP11: shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP12
        sub     bx, di
        or      si, 1

SKIP12: shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP13
        sub     bx, di
        or      si, 1

SKIP13: shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP14
        sub     bx, di
        or      si, 1

SKIP14: shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP15
        sub     bx, di
        or      si, 1

SKIP15: shl     ax, 1                   ; iteration 16 of 16 (last - no more bits of W remain after this)
        rcl     dx, 1
        rcl     bx, 1
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1
        shl     si, 1
        mov     di, si
        shl     di, 1
        or      di, 1
        cmp     bx, di
        jb      SKIP16
        sub     bx, di
        or      si, 1

SKIP16: mov     ax, si                  ; result: root, fully assembled bit by bit
    }
}

/* this loop version trades ~260 fewer cycles for ~218 fewer bytes versus the unrolled version,
 * a worse cycles-per-byte trade than the 6-bit shifts in fxp_mul/ fxp_div, but it's considerably easier to read
 */
/*
fxp16_t fxp_sqrt(fxp16_t x) {
    __asm {
        .8086
        or      ax, ax                  ; test sign of x
        jns     SQRT                    ; non-negative -> continue normally
        int     0                       ; negative -> deliberate panic (see fxp_sqrt's header comment)

SQRT:   xor     dx, dx                  ; zero-extend x into dx:ax (x is >=0, confirmed above)
        shl     ax, 1                   ; unrolled here regardless - only 6 iterations,
        rcl     dx, 1                   ; same favourable trade already proven for
        shl     ax, 1                   ; fxp_mul/fxp_div's rescale (see above)
        rcl     dx, 1
        shl     ax, 1
        rcl     dx, 1
        shl     ax, 1
        rcl     dx, 1
        shl     ax, 1
        rcl     dx, 1
        shl     ax, 1
        rcl     dx, 1                   ; dx:ax = W, ready for extraction

        xor     bx, bx                  ; rem = 0
        xor     si, si                  ; root = 0
        mov     cx, 16                  ; loop counter - exactly one pass per output bit

L0:     shl     ax, 1                   ; extract 2 bits of W into rem, one bit at a
        rcl     dx, 1                   ; time - no single 8086 instruction does this,
        rcl     bx, 1                   ; each carry-chain step moves exactly one bit
        shl     ax, 1
        rcl     dx, 1
        rcl     bx, 1                   ; bx now holds this iteration's rem, 2 bits richer

        shl     si, 1                   ; root <<= 1 - make room for this iteration's guess bit
        mov     di, si                  ; di = scratch, used to build the candidate
        shl     di, 1
        or      di, 1                   ; candidate = (root<<1)|1

        cmp     bx, di                  ; can we afford to subtract this candidate?
        jb      SKIP                    ; no - leave this root bit as 0, skip the subtract
        sub     bx, di                  ; yes - rem -= candidate
        or      si, 1                   ; and set this iteration's root bit to 1
SKIP:   loop    L0                      ; decrement cx, repeat until all 16 bits done

        mov     ax, si                  ; result: root, fully assembled bit by bit
    }
}
*/
